#!/usr/bin/env bash
set -euo pipefail

checker=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)/check-plan.sh

expect_status() {
  local expected=$1 input=$2
  shift 2
  local actual=0
  bash "$checker" "$@" <<< "$input" >/dev/null 2>&1 || actual=$?
  [[ $actual == "$expected" ]] || {
    printf 'expected exit %s, got %s for %s\n' "$expected" "$actual" "$input" >&2
    exit 1
  }
}

expect_status 0 '{"format_version":"1.2","resource_changes":[]}'
expect_status 0 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["no-op"]}}]}'
expect_status 0 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"],"after":{"vm_id":9900,"name":"r720-disposable","pool_id":"tofu-vms","cpu":[{"cores":2}],"memory":[{"dedicated":4096}],"network_device":[{"bridge":"vmbr0"}],"disk":[{"datastore_id":"fast-vm","file_format":"raw","import_from":"local:import/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"}],"agent":[{"enabled":true}],"initialization":[{"ip_config":[{"ipv4":[{"address":"dhcp"}]}]}]}}}]}' --disposable-create
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.other.proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"],"after":{"vm_id":9900,"pool_id":"tofu-vms","network_device":[{"bridge":"vmbr0"}],"disk":[{"datastore_id":"fast-vm","import_from":"local:import/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"}]}}}]}' --disposable-create
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"],"after":{"vm_id":9900,"pool_id":"other","network_device":[{"bridge":"vmbr0"}],"disk":[{"datastore_id":"fast-vm","import_from":"local:import/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"}]}}}]}' --disposable-create
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"],"after":{"vm_id":9900,"pool_id":"tofu-vms","network_device":[{"bridge":"vmbr0"}],"disk":[{"datastore_id":"other","import_from":"local:import/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"}]}}}]}' --disposable-create
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"],"after":{"vm_id":9900,"pool_id":"tofu-vms","network_device":[{"bridge":"other"}],"disk":[{"datastore_id":"fast-vm","import_from":"local:import/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"}]}}}]}' --disposable-create
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"],"after":{"vm_id":9900,"name":"other","pool_id":"tofu-vms","cpu":[{"cores":2}],"memory":[{"dedicated":4096}],"network_device":[{"bridge":"vmbr0"}],"disk":[{"datastore_id":"fast-vm","file_format":"raw","import_from":"local:import/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2"}],"initialization":[{"ip_config":[{"ipv4":[{"address":"dhcp"}]}]}]}}}]}' --disposable-create
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"proxmox_storage_zfspool.bad","type":"proxmox_storage_zfspool","change":{"actions":["create"]}}]}'
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["delete","create"]}}]}'
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["delete"]}}]}'
expect_status 0 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["delete"]}}]}' --disposable-destroy
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.fedora.proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["delete"]}}]}' --disposable-destroy
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.disposable[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["delete"]}},{"address":"module.other.proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"]}}]}' --disposable-destroy
expect_status 1 '{not json}'
expect_status 0 '{"format_version":"1.2"}'
expect_status 1 '{"not_format_version":"1.2"}'
expect_status 1 '{"format_version":1.2,"resource_changes":[]}'
expect_status 0 '{"format_version":"1.2","resource_changes":[{"address":"module.fedora[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"],"after":{"vm_id":100,"name":"fedora-dev","node_name":"pve","pool_id":"tofu-vms","cpu":[{"cores":8,"type":"host"}],"memory":[{"dedicated":32768}],"network_device":[{"bridge":"vmbr0","model":"virtio"}],"disk":[{"datastore_id":"fast-vm","file_format":"raw","import_from":"local:import/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2","interface":"scsi0","size":300}],"agent":[{"enabled":true,"wait_for_ip":[{"disabled":true}]}],"operating_system":[{"type":"l26"}],"initialization":[{"ip_config":[{"ipv4":[{"address":"dhcp"}]}],"user_account":[{"username":"mpeter"}]}],"on_boot":true,"protection":true,"started":true,"stop_on_destroy":true}}}]}' --fedora-create
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.fedora[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["create"],"after":{"vm_id":100,"name":"fedora-dev","node_name":"pve","pool_id":"tofu-vms","cpu":[{"cores":8,"type":"host"}],"memory":[{"dedicated":32768}],"network_device":[{"bridge":"vmbr0","model":"virtio"}],"disk":[{"datastore_id":"fast-vm","file_format":"raw","import_from":"local:import/Fedora-Cloud-Base-Generic-44-1.7.x86_64.qcow2","interface":"scsi0","size":300}],"agent":[{"enabled":true,"wait_for_ip":[{"disabled":true}]}],"operating_system":[{"type":"l26"}],"initialization":[{"ip_config":[{"ipv4":[{"address":"dhcp"}]}],"user_account":[{"username":"mpeter"}]}],"on_boot":true,"protection":false,"started":true,"stop_on_destroy":true}}}]}' --fedora-create
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.fedora[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["delete"]}}]}' --fedora-create
expect_status 0 '{"format_version":"1.2","resource_changes":[{"address":"module.fedora[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["update"],"before":{"vm_id":100,"name":"fedora-dev","started":false},"after":{"vm_id":100,"name":"fedora-dev","node_name":"pve","pool_id":"tofu-vms","cpu":[{"cores":8,"type":"host"}],"memory":[{"dedicated":32768}],"network_device":[{"bridge":"vmbr0"}],"disk":[{"datastore_id":"fast-vm","file_format":"raw","size":300}],"agent":[{"enabled":true,"wait_for_ip":[{"disabled":true}]}],"operating_system":[{"type":"l26"}],"on_boot":true,"protection":true,"started":true,"stop_on_destroy":true}}}]}' --fedora-start
expect_status 1 '{"format_version":"1.2","resource_changes":[{"address":"module.fedora[0].proxmox_virtual_environment_vm.this","type":"proxmox_virtual_environment_vm","change":{"actions":["update"],"before":{"vm_id":100,"name":"fedora-dev","started":false},"after":{"vm_id":100,"name":"fedora-dev","node_name":"pve","pool_id":"tofu-vms","cpu":[{"cores":8,"type":"host"}],"memory":[{"dedicated":32768}],"network_device":[{"bridge":"vmbr0"}],"disk":[{"datastore_id":"fast-vm","file_format":"raw","size":300}],"agent":[{"enabled":true,"wait_for_ip":[{"disabled":true}]}],"operating_system":[{"type":"l26"}],"on_boot":true,"protection":false,"started":true,"stop_on_destroy":true}}}]}' --fedora-start
printf 'plan gate tests PASS\n'
